name: Linux build

on:
  pull_request:
    types: [labeled]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash
jobs:
  webots-build:
    if: ${{ contains(github.event.pull_request.labels.*.name, 'test webots build') }}
    strategy:
      fail-fast: false
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
      with:
         submodules: true
         fetch-depth: 15
    - name: Install Webots Compilation Dependencies
      run: |
        sudo scripts/install/linux_compilation_dependencies.sh
    - name: Build Webots
      run: |
        make webots_target -j 12
  build:
    if: ${{ github.event_name == 'push' || contains(github.event.pull_request.labels.*.name, 'test distribution') || contains(github.event.pull_request.labels.*.name, 'test suite') || contains(github.event.pull_request.labels.*.name, 'test worlds') }}
    strategy:
      fail-fast: false
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
      with:
         submodules: true
         fetch-depth: 15
    - name: Install Webots Compilation Dependencies
      run: |
        sudo scripts/install/linux_optional_compilation_dependencies.sh
    - name: Set Commit SHA in Version
      if: ${{ github.event_name == 'schedule' }}
      run: python scripts/packaging/set_commit_and_date_in_version.py $(git log -1 --format='%H')
    - name: Webots Package Creation
      run: |
        export JAVA_HOME=/usr/lib/jvm/java-${{ matrix.JAVA_VERSION }}-openjdk-amd64
        export PATH=$JAVA_HOME/bin:$PATH
        export LIBGL_ALWAYS_SOFTWARE=true
        export ROS_DISTRO=${{ matrix.ROS_DISTRO }}
        make distrib -j 12
